from typing import Any

from .base import FilterInspector, PaginatorInspector

class CoreAPICompatInspector(PaginatorInspector, FilterInspector):
    def get_paginator_parameters(self, paginator: Any): ...
    def get_filter_parameters(self, filter_backend: Any): ...
    def coreapi_field_to_parameter(self, field: Any): ...

class DjangoRestResponsePagination(PaginatorInspector):
    def get_paginated_response(self, paginator: Any, response_schema: Any): ...
