from typing import Any, Optional, Dict, List

SWAGGER_DEFAULTS: Dict[str, Any]  # Could use TypedDict here
REDOC_DEFAULTS: Dict[str, Any]
IMPORT_STRINGS: List[str]

class AppSettings:
    defaults: Any = ...
    import_strings: Any = ...
    def __init__(self, user_settings: Any, defaults: Any, import_strings: Optional[Any] = ...): ...
    @property
    def user_settings(self): ...
    def __getattr__(self, attr: Any): ...

swagger_settings: Any
redoc_settings: Any
