from typing import Any, Optional

class SwaggerError(Exception): ...

class SwaggerValidationError(SwaggerError):
    errors: Any = ...
    spec: Any = ...
    source_codec: Any = ...
    def __init__(
        self,
        msg: Any,
        errors: Optional[Any] = ...,
        spec: Optional[Any] = ...,
        source_codec: Optional[Any] = ...,
        *args: Any
    ): ...

class SwaggerGenerationError(SwaggerError): ...
