from typing import Any, Optional

from rest_framework.schemas.generators import EndpointEnumerator as _EndpointEnumerator

PATH_PARAMETER_RE: Any

class EndpointEnumerator(_EndpointEnumerator):
    request: Any = ...
    def __init__(self, patterns: Optional[Any] = ..., urlconf: Optional[Any] = ..., request: Optional[Any] = ...): ...
    def get_path_from_regex(self, path_regex: Any): ...
    def should_include_endpoint(
        self, path: Any, callback: Any, app_name: str = ..., namespace: str = ..., url_name: Optional[Any] = ...
    ): ...
    def replace_version(self, path: Any, callback: Any): ...
    def get_api_endpoints(
        self,
        patterns: Optional[Any] = ...,
        prefix: str = ...,
        app_name: Optional[Any] = ...,
        namespace: Optional[Any] = ...,
        ignored_endpoints: Optional[Any] = ...,
    ): ...
    def unescape(self, s: Any): ...
    def unescape_path(self, path: Any): ...

class OpenAPISchemaGenerator:
    endpoint_enumerator_class: Any = ...
    reference_resolver_class: Any = ...
    info: Any = ...
    version: Any = ...
    consumes: Any = ...
    produces: Any = ...
    def __init__(
        self,
        info: Any,
        version: str = ...,
        url: Optional[Any] = ...,
        patterns: Optional[Any] = ...,
        urlconf: Optional[Any] = ...,
    ): ...
    @property
    def url(self): ...
    def get_security_definitions(self): ...
    def get_security_requirements(self, security_definitions: Any): ...
    def get_schema(self, request: Optional[Any] = ..., public: bool = ...): ...
    def create_view(self, callback: Any, method: Any, request: Optional[Any] = ...): ...
    def coerce_path(self, path: Any, view: Any): ...
    def get_endpoints(self, request: Any): ...
    def get_operation_keys(self, subpath: Any, method: Any, view: Any): ...
    def determine_path_prefix(self, paths: Any): ...
    def should_include_endpoint(self, path: Any, method: Any, view: Any, public: Any): ...
    def get_paths_object(self, paths: Any): ...
    def get_paths(self, endpoints: Any, components: Any, request: Any, public: Any): ...
    def get_operation(self, view: Any, path: Any, prefix: Any, method: Any, components: Any, request: Any): ...
    def get_path_item(self, path: Any, view_cls: Any, operations: Any): ...
    def get_overrides(self, view: Any, method: Any): ...
    def get_path_parameters(self, path: Any, view_cls: Any): ...
