from typing import Any, Optional

logger: Any

class no_body: ...
class unset: ...

def swagger_auto_schema(
    method: Optional[Any] = ...,
    methods: Optional[Any] = ...,
    auto_schema: Any = ...,
    request_body: Optional[Any] = ...,
    query_serializer: Optional[Any] = ...,
    manual_parameters: Optional[Any] = ...,
    operation_id: Optional[Any] = ...,
    operation_description: Optional[Any] = ...,
    operation_summary: Optional[Any] = ...,
    security: Optional[Any] = ...,
    deprecated: Optional[Any] = ...,
    responses: Optional[Any] = ...,
    field_inspectors: Optional[Any] = ...,
    filter_inspectors: Optional[Any] = ...,
    paginator_inspectors: Optional[Any] = ...,
    tags: Optional[Any] = ...,
    **extra_overrides: Any
): ...
def swagger_serializer_method(serializer_or_field: Any): ...
def is_list_view(path: Any, method: Any, view: Any): ...
def guess_response_status(method: Any): ...
def param_list_to_odict(parameters: Any): ...
def merge_params(parameters: Any, overrides: Any): ...
def filter_none(obj: Any): ...
def force_serializer_instance(serializer: Any): ...
def get_serializer_class(serializer: Any): ...
def get_object_classes(classes_or_instances: Any, expected_base_class: Optional[Any] = ...): ...
def get_consumes(parser_classes: Any): ...
def get_produces(renderer_classes: Any): ...
def decimal_as_float(field: Any): ...
def get_serializer_ref_name(serializer: Any): ...
def force_real_str(s: Any, encoding: str = ..., strings_only: bool = ..., errors: str = ...): ...
def field_value_to_representation(field: Any, value: Any): ...
def get_field_default(field: Any): ...
def dict_has_ordered_keys(obj: Any): ...
